src/Entity/Hours.php
<?php

namespace App\Entity;

use App\Repository\HoursRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractDashboardController;

#[ORM\Entity(repositoryClass: HoursRepository::class)]
class Hours extends AbstractDashboardController
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 20)]
    private ?string $day_of_week = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $open_am = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $close_am = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $open_pm = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $close_pm = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDayOfWeek(): ?string
    {
        return $this->day_of_week;
    }

    public function setDayOfWeek(string $day_of_week): static
    {
        $this->day_of_week = $day_of_week;

        return $this;
    }

    public function getOpenAm(): ?\DateTimeInterface
    {
        return $this->open_am;
    }

    public function setOpenAm(\DateTimeInterface $open_am): static
    {
        $this->open_am = $open_am;

        return $this;
    }

    public function getCloseAm(): ?\DateTimeInterface
    {
        return $this->close_am;
    }

    public function setCloseAm(\DateTimeInterface $close_am): static
    {
        $this->close_am = $close_am;

        return $this;
    }

    public function getOpenPm(): ?\DateTimeInterface
    {
        return $this->open_pm;
    }

    public function setOpenPm(\DateTimeInterface $open_pm): static
    {
        $this->open_pm = $open_pm;

        return $this;
    }

    public function getClosePm(): ?\DateTimeInterface
    {
        return $this->close_pm;
    }

    public function setClosePm(\DateTimeInterface $close_pm): static
    {
        $this->close_pm = $close_pm;

        return $this;
    }
}

src/Form/HoursType.php
<?php

namespace App\Form;

use App\Entity\Hours;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class HoursType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('day_of_week')
            ->add('open_am')
            ->add('close_am')
            ->add('open_pm')
            ->add('close_pm')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Hours::class,
        ]);
    }
}

src/Controller/HoursController.php
<?php

namespace App\Controller;

use App\Entity\Hours;
use App\Form\HoursType;
use App\Repository\HoursRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/hours')]
class HoursController extends AbstractController
{
    #[Route('/', name: 'app_hours_index', methods: ['GET'])]
    public function index(HoursRepository $hoursRepository): Response
    {
        return $this->render('hours/index.html.twig', [
            'hours' => $hoursRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_hours_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $hour = new Hours();
        $form = $this->createForm(HoursType::class, $hour);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($hour);
            $entityManager->flush();

            return $this->redirectToRoute('app_hours_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('hours/new.html.twig', [
            'hour' => $hour,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_hours_show', methods: ['GET'])]
    public function show(Hours $hour): Response
    {
        return $this->render('hours/show.html.twig', [
            'hour' => $hour,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_hours_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Hours $hour, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(HoursType::class, $hour);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_hours_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('hours/edit.html.twig', [
            'hour' => $hour,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_hours_delete', methods: ['POST'])]
    public function delete(Request $request, Hours $hour, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$hour->getId(), $request->request->get('_token'))) {
            $entityManager->remove($hour);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_hours_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/hours/_delete_form.html.twig
<form method="post" action="{{ path('app_hours_delete', {'id': hour.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ hour.id) }}">
    <button class="btn">Delete</button>
</form>

templates/hours/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/hours/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Hours{% endblock %}

{% block body %}
    <h1>Edit Hours</h1>

    {{ include('hours/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_hours_index') }}">back to list</a>

    {{ include('hours/_delete_form.html.twig') }}
{% endblock %}

templates/hours/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hours index{% endblock %}

{% block body %}
    <h1>Hours index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Day_of_week</th>
                <th>Open_am</th>
                <th>Close_am</th>
                <th>Open_pm</th>
                <th>Close_pm</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for hour in hours %}
            <tr>
                <td>{{ hour.id }}</td>
                <td>{{ hour.dayOfWeek }}</td>
                <td>{{ hour.openAm ? hour.openAm|date('H:i:s') : '' }}</td>
                <td>{{ hour.closeAm ? hour.closeAm|date('H:i:s') : '' }}</td>
                <td>{{ hour.openPm ? hour.openPm|date('H:i:s') : '' }}</td>
                <td>{{ hour.closePm ? hour.closePm|date('H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_hours_show', {'id': hour.id}) }}">show</a>
                    <a href="{{ path('app_hours_edit', {'id': hour.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_hours_new') }}">Create new</a>
{% endblock %}

templates/hours/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Hours{% endblock %}

{% block body %}
    <h1>Create new Hours</h1>

    {{ include('hours/_form.html.twig') }}

    <a href="{{ path('app_hours_index') }}">back to list</a>
{% endblock %}

templates/hours/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hours{% endblock %}

{% block body %}
    <h1>Hours</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ hour.id }}</td>
            </tr>
            <tr>
                <th>Day_of_week</th>
                <td>{{ hour.dayOfWeek }}</td>
            </tr>
            <tr>
                <th>Open_am</th>
                <td>{{ hour.openAm ? hour.openAm|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Close_am</th>
                <td>{{ hour.closeAm ? hour.closeAm|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Open_pm</th>
                <td>{{ hour.openPm ? hour.openPm|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Close_pm</th>
                <td>{{ hour.closePm ? hour.closePm|date('H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_hours_index') }}">back to list</a>

    <a href="{{ path('app_hours_edit', {'id': hour.id}) }}">edit</a>

    {{ include('hours/_delete_form.html.twig') }}
{% endblock %}